### ISSUE TITLE
What distro is it for

### ISSUE THREAD

**Issue by Nickelbawker** [B00merang-Project/Mac-OS-X-Cheetah#3]
What distro and version are you developing this for?

I've sent a message on twitter and boomerang maybe better to ask on here. I have a current Manjaro gnome or Ubuntu gnome iso but willing to switch. Couldn't get the shell working on Manjaro and on Ubuntu I couldn't get the extension working. Not sure what I'm missing I believe them both to have had Murrine, gtk3 and pixmap. Haven't done much linux theming but I personally feel this was the most cool looking OS ever, Vista was a close second but has already been decently represented for Win10 and 7. Also Vista has a larger library of modern programs than original OS X so it would be really cool for me to have this theme running on linux. Thanks!

**Comment by Elbullazul** [comment]
hello,

this theme has support works for GNOME and Cinnamon desktops, with partial support for MATE and Xfce.

For GNOME, you need gnomet-tweaks installed and the [User Themes](https://extensions.gnome.org/extension/19/user-themes/) shell extension enabled. Once installed, you can change the shell theme in the Tweaks app
