### ISSUE TITLE
Release 1.1 in Ubuntu 20.04

### ISSUE THREAD

**Issue by OliverUrbann** [B00merang-Project/Mac-OS-X-Cheetah#4]
Hi all,

First let me say, I've searched 15 years for a theme that looks like early Mac OS X, so thank you very much for this theme. I'd prefer to continue to use the release 1.1 on my new Ubuntu 20.04. However, on some windows the grey lines in the white window bars become transparent in some windows. Is it a new "feature" of 20.04 (transparency) that I can deactivate?

**Comment by Elbullazul** [comment]
hello,

can you post screenshots illustrating the issue?

**Comment by OliverUrbann** [comment]
Sure. Not all windows are affected, actually only a few. Here is one.
![grafik](https://user-images.githubusercontent.com/13621807/105577846-4af79700-5d7c-11eb-8c9f-68d2c550b92a.png)

**Comment by Elbullazul** [comment]
looks weird, will have a look next time I work on themes

**Comment by Elbullazul** [comment]
Just an opacity inconsistency. You'll need to replace the following snippet from gtk-3.20/gtk-widgets.css, at line 2670:

```css
  background-image: linear-gradient(to bottom, @titlebar_bg_color 35%, alpha(@borders, 0.7) 40%, alpha(@borders, 0.7) 64%, @titlebar_bg_color 85%); }
```

with this:
```css
  background-image: linear-gradient(to bottom, @titlebar_bg_color 35%, shade(@borders, 1.05) 40%, shade(@borders, 1.05) 64%, @titlebar_bg_color 85%); }
```

Any reason why you prefer the 1.1 release?

**Comment by OliverUrbann** [comment]
My feeling is it looks closer to the original one. Version 1.2 and newer has just black thinner lines on white, while 1.1 has wider gray lines.

**Comment by Elbullazul** [comment]
I checked a few screenshots and you seem correct. I'll change it so that it looks like it did in 1.1

**Comment by Elbullazul** [comment]
12a4457 restores the previous stripes
